// Used For the Purpose of tracking Event reservation 
'use strict';

let mongoose = require('mongoose'),
	Schema = mongoose.Schema;

let ProductSchema = new Schema({
	  "Product_Category_Code": Number,
	  "Product_Category_Name": String,
    "Product_Group": Number,
    "Product_Group_Name": String,
    "Product_Code": Number,
    "Product_Name": String,
    "NOBB": String,
    "Description": String,
    "Description_2": String,
    "Storageunit": String,
    "Billingunit": String,
    "Billing_Cost_Larvik": Number,
    "Billing_Cost_Andalsnes": Number,
    "Billing_Cost_Drammen": Number,
    "Billing_Cost": Number,
    "Available_Larvik": Number,
    "Available_Andalsnes": Number,
    "Available_Drammen": Number,
    "Antall_I_ordre": Number,
    "Antall_I_Bestilling": Number,
    "Transitt": Number,
    "Leverandørnr.": Number,
    "Kolonne1": Number,
    "Kolonne2": Number,
    "Varesporingskode": Number
});

ProductSchema.index({
  Product_Category_Code: 1,
  Product_Group: 1
},
  {
    NOBB: "text",
    Description: "text",
    Description_2: "text",
    Storageunit: "text",
    Billingunit: "text",
    Product_Category_Name: "text",
    Product_Group_Name: "text",
    Product_Name: 'text'
  }
)


module.exports = mongoose.model('Products', ProductSchema);

// [
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 150000000000000000,
//     "NOBB": null,
//     "Description": "DIVERSE KONSTRUKSJON",
//     "Description_2": "",
//     "Storageunit": "M2",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 66.31,
//     "Billing_Cost_Andalsnes": 161.6,
//     "Billing_Cost_Drammen": 66.31,
//     "Billing_Cost": 0,
//     "Available_Larvik": "317.08",
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151001204224000600,
//     "NOBB": 48784101,
//     "Description": "KONSTR XF WEATHERGUARD TG2",
//     "Description_2": "12MM 2400X0610MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 45.05,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 45.05,
//     "Billing_Cost": 130,
//     "Available_Larvik": "926.00",
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151001204224001200,
//     "NOBB": 44888056,
//     "Description": "KONSTR XF WEATHERGUARD TG2",
//     "Description_2": "12MM 2400X1207MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 44.05,
//     "Billing_Cost_Andalsnes": 46.07,
//     "Billing_Cost_Drammen": 44.52,
//     "Billing_Cost": 121,
//     "Available_Larvik": 2051.00,
//     "Available_Andalsnes": 618,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 6.375,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151001504224001200,
//     "NOBB": 44888302,
//     "Description": "KONSTR XF WEATHERGUARD TG2",
//     "Description_2": "15MM 2400X1207MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 55.57,
//     "Billing_Cost_Andalsnes": 57.52,
//     "Billing_Cost_Drammen": 55.93,
//     "Billing_Cost": 144,
//     "Available_Larvik": 7499.00,
//     "Available_Andalsnes": 1701.00,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 65,
//     "Antall_I_Bestilling": 3.64,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151001504324100600,
//     "NOBB": 45224181,
//     "Description": "KONSTR XF WEATHERGUARD TG4",
//     "Description_2": "15MM 2410X0610MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 57.77,
//     "Billing_Cost_Andalsnes": 60.95,
//     "Billing_Cost_Drammen": 58.17,
//     "Billing_Cost": 154,
//     "Available_Larvik": 14013.00,
//     "Available_Andalsnes": 455,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 2.73,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151001804224001200,
//     "NOBB": 44888321,
//     "Description": "KONSTR XF WEATHERGUARD TG2",
//     "Description_2": "18MM 2400X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 66.94,
//     "Billing_Cost_Andalsnes": 74.45,
//     "Billing_Cost_Drammen": 66.94,
//     "Billing_Cost": 177,
//     "Available_Larvik": 3642.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 180,
//     "Antall_I_Bestilling": 3.465,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151001804324100600,
//     "NOBB": 44888366,
//     "Description": "KONSTR XF WEATHERGUARD TG4",
//     "Description_2": "18MM 2410X0610MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 72.35,
//     "Billing_Cost_Andalsnes": 72.44,
//     "Billing_Cost_Drammen": 71.91,
//     "Billing_Cost": 189,
//     "Available_Larvik": 1320.00,
//     "Available_Andalsnes": 757,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 2.42,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151001804324101220,
//     "NOBB": 45659403,
//     "Description": "KONSTR XF WEATHERGUARD TG4",
//     "Description_2": "18MM 2410X1210MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 75.96,
//     "Billing_Cost_Andalsnes": 72.26,
//     "Billing_Cost_Drammen": 72.71,
//     "Billing_Cost": 183,
//     "Available_Larvik": 14.00,
//     "Available_Andalsnes": 101,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 495,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151001804424001200,
//     "NOBB": 49667452,
//     "Description": "KONSTR XF WEATERGUARD SK",
//     "Description_2": "18MM 2400X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 62.13,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 62.13,
//     "Billing_Cost": 176,
//     "Available_Larvik": 545.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 1.1,
//     "Antall_I_Bestilling": 990,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151002104224001200,
//     "NOBB": 44888340,
//     "Description": "KONSTR XF WEATHERGUARD TG2",
//     "Description_2": "21MM 2400X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 78.12,
//     "Billing_Cost_Andalsnes": 89.66,
//     "Billing_Cost_Drammen": 78.12,
//     "Billing_Cost": 205,
//     "Available_Larvik": 878.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151002104324100600,
//     "NOBB": 44888374,
//     "Description": "KONSTR XF WEATHERGUARD TG4",
//     "Description_2": "21MM 2410X0610MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 80.52,
//     "Billing_Cost_Andalsnes": 85.66,
//     "Billing_Cost_Drammen": 82.51,
//     "Billing_Cost": 217,
//     "Available_Larvik": 980.00,
//     "Available_Andalsnes": 615,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151002404224001200,
//     "NOBB": 46614714,
//     "Description": "KONSTR XF WEATHERGUARD TG2",
//     "Description_2": "24MM 2400X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 89.19,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 89.19,
//     "Billing_Cost": 236,
//     "Available_Larvik": 69.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151002404324000600,
//     "NOBB": 48152837,
//     "Description": "KONSTR XF WEATHERGUARD TG4",
//     "Description_2": "24MM 2410X0610MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 97.48,
//     "Billing_Cost_Drammen": 94.66,
//     "Billing_Cost": 263,
//     "Available_Larvik": 480.00,
//     "Available_Andalsnes": 283,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151002404424001200,
//     "NOBB": 49667463,
//     "Description": "KONSTR XF WEATERGUARD SK",
//     "Description_2": "24MM 2400X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 86.84,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 86.84,
//     "Billing_Cost": 233,
//     "Available_Larvik": 80.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 280,
//     "Antall_I_Bestilling": 80,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1510,
//     "Product_Code": 151004004424001200,
//     "NOBB": 49667478,
//     "Description": "KONSTR XF WEATERGUARD SK",
//     "Description_2": "40MM 2400X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 223.07,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 223.07,
//     "Billing_Cost": 588,
//     "Available_Larvik": 92.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 120,
//     "Antall_I_Bestilling": 90,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1515,
//     "Product_Code": 151501204224001200,
//     "NOBB": null,
//     "Description": "KONSTR XF GRAN TG2",
//     "Description_2": "12MM 2400X1210MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 0,
//     "Billing_Cost": 0,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1515,
//     "Product_Code": 151501205224001200,
//     "NOBB": 49015536,
//     "Description": "KONSTR GRAN III/III TG2",
//     "Description_2": "12MM 2400X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 38.82,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 38.84,
//     "Billing_Cost": 108,
//     "Available_Larvik": 3207.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1515,
//     "Product_Code": 151501505224001200,
//     "NOBB": 49015540,
//     "Description": "KONSTR GRAN III/III TG2",
//     "Description_2": "15MM 2400X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 49.62,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 49.62,
//     "Billing_Cost": 127,
//     "Available_Larvik": 220.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 310,
//     "Antall_I_Bestilling": 4.095,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1515,
//     "Product_Code": 151501804024001200,
//     "NOBB": null,
//     "Description": "KONSTR XF GRAN TG2 II/III",
//     "Description_2": "18MM 2400X1210MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 0,
//     "Billing_Cost": 0,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1515,
//     "Product_Code": 151501804024100600,
//     "NOBB": null,
//     "Description": "KONSTR XF GRAN TG4 II/III",
//     "Description_2": "18MM 2410X0610MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 0,
//     "Billing_Cost": 0,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1515,
//     "Product_Code": 151501804224000600,
//     "NOBB": null,
//     "Description": "KONSTR XF GRAN TG2",
//     "Description_2": "18MM 2400X0610MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 0,
//     "Billing_Cost": 153,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1515,
//     "Product_Code": 151501805224001200,
//     "NOBB": 49015555,
//     "Description": "KONSTR GRAN III/III TG2",
//     "Description_2": "18MM 2400X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 61.53,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 61.63,
//     "Billing_Cost": 157,
//     "Available_Larvik": 1948.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 275,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1515,
//     "Product_Code": 151502104224001200,
//     "NOBB": null,
//     "Description": "KONSTR XF GRAN TG2",
//     "Description_2": "21MM 2400X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 70.14,
//     "Billing_Cost": 167,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1520,
//     "Product_Code": 152001204224001200,
//     "NOBB": 50983641,
//     "Description": "KONSTR XF FURU SUDPLY TG2",
//     "Description_2": "12MM 2400X1200MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 34.66,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 34.65,
//     "Billing_Cost": 101,
//     "Available_Larvik": 7488.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 75,
//     "Antall_I_Bestilling": 2.1,
//     "Transitt": 0,
//     "Leverandørnr": 100707,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1520,
//     "Product_Code": 152001504224001200,
//     "NOBB": 50983637,
//     "Description": "KONSTR XF FURU SUDPLY TG2",
//     "Description_2": "15MM 2400X1200MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 43.45,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 43.45,
//     "Billing_Cost": 120,
//     "Available_Larvik": 8703.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 37,
//     "Antall_I_Bestilling": 720,
//     "Transitt": 0,
//     "Leverandørnr": 100707,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1520,
//     "Product_Code": 152001804224001200,
//     "NOBB": 50983622,
//     "Description": "KONSTR XF FURU SUDPLY TG2",
//     "Description_2": "18MM 2400X1200MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 51.38,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 51.34,
//     "Billing_Cost": 148,
//     "Available_Larvik": 4911.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 2.5,
//     "Transitt": 0,
//     "Leverandørnr": 100707,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1530,
//     "Product_Code": 153000900023401200,
//     "NOBB": 47154285,
//     "Description": "KRYSSFINER SOPP/RÅTE BEH TG2",
//     "Description_2": "9MM 2340X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 46.5,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 46.5,
//     "Billing_Cost": 136,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100445,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1530,
//     "Product_Code": 153000900027601200,
//     "NOBB": null,
//     "Description": "KRYSSFINER SOPP/RÅTE BEH SK",
//     "Description_2": "9MM 2760X1200MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 41,
//     "Billing_Cost": 0,
//     "Available_Larvik": -450.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 500,
//     "Antall_I_Bestilling": 1.35,
//     "Transitt": 0,
//     "Leverandørnr": 101462,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1530,
//     "Product_Code": 153000900027601200,
//     "NOBB": 47154293,
//     "Description": "KRYSSFINER SOPP/RÅTE BEH TG2",
//     "Description_2": "9MM 2760X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 51.2,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 51.2,
//     "Billing_Cost": 140,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100445,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1530,
//     "Product_Code": 153000904424001200,
//     "NOBB": 47557932,
//     "Description": "KONST XF MOULDGUARD SK",
//     "Description_2": "9MM 2400X1200MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 0,
//     "Billing_Cost": 117,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100683,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1530,
//     "Product_Code": 153001204224001200,
//     "NOBB": 47557943,
//     "Description": "KONST XF MOULDGUARD TG2",
//     "Description_2": "12MM 2400X1207MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 0,
//     "Billing_Cost": 148,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100683,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1530,
//     "Product_Code": 153001504224001200,
//     "NOBB": 47557958,
//     "Description": "KONST XF MOULDGUARD TG2",
//     "Description_2": "15MM 2400X1207MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 63.34,
//     "Billing_Cost": 187,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100683,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1540,
//     "Product_Code": 154000000000000000,
//     "NOBB": null,
//     "Description": "DIVERSE BRANNHEMMENDE X-FINER",
//     "Description_2": "",
//     "Storageunit": "M2",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 212.77,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 212.77,
//     "Billing_Cost": 573,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1540,
//     "Product_Code": 154001202024401200,
//     "NOBB": 47271401,
//     "Description": "KRYSSFINER BRANNX B B/BB",
//     "Description_2": "12MM 2440X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 171.71,
//     "Billing_Cost_Andalsnes": 170.6,
//     "Billing_Cost_Drammen": 170.6,
//     "Billing_Cost": 418,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 60,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1540,
//     "Product_Code": 154001204324100600,
//     "NOBB": 47154796,
//     "Description": "KRYSSFINER BRANNX S TG4",
//     "Description_2": "12MM 2410X0610MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 112.65,
//     "Billing_Cost_Drammen": 112.65,
//     "Billing_Cost": 345,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 464,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1540,
//     "Product_Code": 154001502424401200,
//     "NOBB": 49668477,
//     "Description": "KRYSSFINER BRANNX B BB/CP",
//     "Description_2": "15MM 2440X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 161.14,
//     "Billing_Cost_Drammen": 161.14,
//     "Billing_Cost": 807,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 40,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1540,
//     "Product_Code": 154001504224001200,
//     "NOBB": 47154853,
//     "Description": "KRYSSFINER FIRE RESIST TG2(S2)",
//     "Description_2": "15MM 2400X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 125,
//     "Billing_Cost_Andalsnes": 116.82,
//     "Billing_Cost_Drammen": 116.82,
//     "Billing_Cost": 377,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 122,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1540,
//     "Product_Code": 154001804224001200,
//     "NOBB": 47154845,
//     "Description": "KRYSSFINER FIRE RESIST TG2(S2)",
//     "Description_2": "18MM 2400X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 130.28,
//     "Billing_Cost_Drammen": 131.52,
//     "Billing_Cost": 453,
//     "Available_Larvik": 66.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": 100719,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1540,
//     "Product_Code": 154001804324100600,
//     "NOBB": 47154800,
//     "Description": "KRYSSFINER BRANNX S TG4",
//     "Description_2": "18MM 2410X0610MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 162.41,
//     "Billing_Cost_Drammen": 162.41,
//     "Billing_Cost": 474,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 336,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1540,
//     "Product_Code": 154001804524401200,
//     "NOBB": null,
//     "Description": "KRYSSFINER BRANNX P",
//     "Description_2": "18MM 2440X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 188.76,
//     "Billing_Cost_Drammen": 184.94,
//     "Billing_Cost": 429,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 44,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1540,
//     "Product_Code": 154002104324100600,
//     "NOBB": 47154815,
//     "Description": "KRYSSFINER BRANNX S TG4",
//     "Description_2": "21MM 2410X0610MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 187.42,
//     "Billing_Cost_Andalsnes": 192.3,
//     "Billing_Cost_Drammen": 192.3,
//     "Billing_Cost": 571,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": -56,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 56,
//     "Antall_I_Bestilling": 1.17,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1540,
//     "Product_Code": 154002404324100600,
//     "NOBB": 47154826,
//     "Description": "KRYSSFINER BRANNX S TG4",
//     "Description_2": "24MM 2410X0610MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 235.14,
//     "Billing_Cost_Andalsnes": 219.76,
//     "Billing_Cost_Drammen": 198.36,
//     "Billing_Cost": 661,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 112,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 640,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1540,
//     "Product_Code": 154002804524401200,
//     "NOBB": null,
//     "Description": "KRYSSFINER BRANNX P",
//     "Description_2": "28MM 2440X1220MM",
//     "Storageunit": "PLA",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 0,
//     "Billing_Cost_Drammen": 297.28,
//     "Billing_Cost": 0,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 35,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   },
//   {
//     "Product_Category_Code": 15,
//     "Product_Group": 1540,
//     "Product_Code": 154010000000000000,
//     "NOBB": null,
//     "Description": "DIVERSE KRYSSFINER BRANNX",
//     "Description_2": "",
//     "Storageunit": "M2",
//     "Billingunit": "M2",
//     "Billing_Cost_Larvik": 0,
//     "Billing_Cost_Andalsnes": 88.46,
//     "Billing_Cost_Drammen": 88.46,
//     "Billing_Cost": 573,
//     "Available_Larvik": 0.00,
//     "Available_Andalsnes": 0,
//     "Available_Drammen": 0,
//     "Antall_I_ordre": 0,
//     "Antall_I_Bestilling": 0,
//     "Transitt": 0,
//     "Leverandørnr": null,
//     "Kolonne1": null,
//     "Kolonne2": null,
//     "Varesporingskode": null
//   }
// ]

/*[
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name",
    "Product_Code": 160000000000000000,
    "NOBB": null,
    "Description": "DIVERSE KONSTRUKSJON",
    "Description_2": "",
    "Storageunit": "M2",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 66.31,
    "Billing_Cost_Andalsnes": 161.6,
    "Billing_Cost_Drammen": 66.31,
    "Billing_Cost": 0,
    "Available_Larvik": "317.08",
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161001204224000600,
    "NOBB": 48784101,
    "Description": "KONSTR XF WEATHERGUARD TG2",
    "Description_2": "12MM 2400X0610MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 45.05,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 45.05,
    "Billing_Cost": 130,
    "Available_Larvik": "926.00",
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161001204224001200,
    "NOBB": 44888056,
    "Description": "KONSTR XF WEATHERGUARD TG2",
    "Description_2": "12MM 2400X1207MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 44.05,
    "Billing_Cost_Andalsnes": 46.07,
    "Billing_Cost_Drammen": 44.52,
    "Billing_Cost": 121,
    "Available_Larvik": 2051.00,
    "Available_Andalsnes": 618,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 6.375,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161001604224001200,
    "NOBB": 44888302,
    "Description": "KONSTR XF WEATHERGUARD TG2",
    "Description_2": "16MM 2400X1207MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 55.57,
    "Billing_Cost_Andalsnes": 57.52,
    "Billing_Cost_Drammen": 55.93,
    "Billing_Cost": 144,
    "Available_Larvik": 7499.00,
    "Available_Andalsnes": 1701.00,
    "Available_Drammen": 0,
    "Antall_I_ordre": 65,
    "Antall_I_Bestilling": 3.64,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161001604324100600,
    "NOBB": 45224181,
    "Description": "KONSTR XF WEATHERGUARD TG4",
    "Description_2": "16MM 2410X0610MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 57.77,
    "Billing_Cost_Andalsnes": 60.95,
    "Billing_Cost_Drammen": 58.17,
    "Billing_Cost": 164,
    "Available_Larvik": 14013.00,
    "Available_Andalsnes": 455,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 2.73,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161001804224001200,
    "NOBB": 44888321,
    "Description": "KONSTR XF WEATHERGUARD TG2",
    "Description_2": "18MM 2400X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 66.94,
    "Billing_Cost_Andalsnes": 74.45,
    "Billing_Cost_Drammen": 66.94,
    "Billing_Cost": 177,
    "Available_Larvik": 3642.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 180,
    "Antall_I_Bestilling": 3.465,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161001804324100600,
    "NOBB": 44888366,
    "Description": "KONSTR XF WEATHERGUARD TG4",
    "Description_2": "18MM 2410X0610MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 72.35,
    "Billing_Cost_Andalsnes": 72.44,
    "Billing_Cost_Drammen": 71.91,
    "Billing_Cost": 189,
    "Available_Larvik": 1320.00,
    "Available_Andalsnes": 757,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 2.42,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161001804324101220,
    "NOBB": 45659403,
    "Description": "KONSTR XF WEATHERGUARD TG4",
    "Description_2": "18MM 2410X1210MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 75.96,
    "Billing_Cost_Andalsnes": 72.26,
    "Billing_Cost_Drammen": 72.71,
    "Billing_Cost": 183,
    "Available_Larvik": 14.00,
    "Available_Andalsnes": 101,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 495,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161001804424001200,
    "NOBB": 49667452,
    "Description": "KONSTR XF WEATERGUARD SK",
    "Description_2": "18MM 2400X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 62.13,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 62.13,
    "Billing_Cost": 176,
    "Available_Larvik": 545.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 1.1,
    "Antall_I_Bestilling": 990,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161002104224001200,
    "NOBB": 44888340,
    "Description": "KONSTR XF WEATHERGUARD TG2",
    "Description_2": "21MM 2400X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 78.12,
    "Billing_Cost_Andalsnes": 89.66,
    "Billing_Cost_Drammen": 78.12,
    "Billing_Cost": 205,
    "Available_Larvik": 878.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161002104324100600,
    "NOBB": 44888374,
    "Description": "KONSTR XF WEATHERGUARD TG4",
    "Description_2": "21MM 2410X0610MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 80.52,
    "Billing_Cost_Andalsnes": 85.66,
    "Billing_Cost_Drammen": 82.51,
    "Billing_Cost": 217,
    "Available_Larvik": 980.00,
    "Available_Andalsnes": 616,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161002404224001200,
    "NOBB": 46614714,
    "Description": "KONSTR XF WEATHERGUARD TG2",
    "Description_2": "24MM 2400X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 89.19,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 89.19,
    "Billing_Cost": 236,
    "Available_Larvik": 69.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161002404324000600,
    "NOBB": 48162837,
    "Description": "KONSTR XF WEATHERGUARD TG4",
    "Description_2": "24MM 2410X0610MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 97.48,
    "Billing_Cost_Drammen": 94.66,
    "Billing_Cost": 263,
    "Available_Larvik": 480.00,
    "Available_Andalsnes": 283,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161002404424001200,
    "NOBB": 49667463,
    "Description": "KONSTR XF WEATERGUARD SK",
    "Description_2": "24MM 2400X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 86.84,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 86.84,
    "Billing_Cost": 233,
    "Available_Larvik": 80.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 280,
    "Antall_I_Bestilling": 80,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1610,
    "Product_Code": 161004004424001200,
    "NOBB": 49667478,
    "Description": "KONSTR XF WEATERGUARD SK",
    "Description_2": "40MM 2400X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 223.07,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 223.07,
    "Billing_Cost": 588,
    "Available_Larvik": 92.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 120,
    "Antall_I_Bestilling": 90,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1616,
    "Product_Code": 161601204224001200,
    "NOBB": null,
    "Description": "KONSTR XF GRAN TG2",
    "Description_2": "12MM 2400X1210MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 0,
    "Billing_Cost": 0,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1616,
    "Product_Code": 161601205224001200,
    "NOBB": 49016536,
    "Description": "KONSTR GRAN III/III TG2",
    "Description_2": "12MM 2400X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 38.82,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 38.84,
    "Billing_Cost": 108,
    "Available_Larvik": 3207.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1616,
    "Product_Code": 161601605224001200,
    "NOBB": 49016540,
    "Description": "KONSTR GRAN III/III TG2",
    "Description_2": "16MM 2400X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 49.62,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 49.62,
    "Billing_Cost": 127,
    "Available_Larvik": 220.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 310,
    "Antall_I_Bestilling": 4.095,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1616,
    "Product_Code": 161601804024001200,
    "NOBB": null,
    "Description": "KONSTR XF GRAN TG2 II/III",
    "Description_2": "18MM 2400X1210MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 0,
    "Billing_Cost": 0,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1616,
    "Product_Code": 161601804024100600,
    "NOBB": null,
    "Description": "KONSTR XF GRAN TG4 II/III",
    "Description_2": "18MM 2410X0610MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 0,
    "Billing_Cost": 0,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1616,
    "Product_Code": 161601804224000600,
    "NOBB": null,
    "Description": "KONSTR XF GRAN TG2",
    "Description_2": "18MM 2400X0610MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 0,
    "Billing_Cost": 163,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1616,
    "Product_Code": 161601805224001200,
    "NOBB": 49016555,
    "Description": "KONSTR GRAN III/III TG2",
    "Description_2": "18MM 2400X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 61.53,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 61.63,
    "Billing_Cost": 167,
    "Available_Larvik": 1948.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 275,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1616,
    "Product_Code": 161602104224001200,
    "NOBB": null,
    "Description": "KONSTR XF GRAN TG2",
    "Description_2": "21MM 2400X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 70.14,
    "Billing_Cost": 167,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1620,
    "Product_Code": 162001204224001200,
    "NOBB": 50983641,
    "Description": "KONSTR XF FURU SUDPLY TG2",
    "Description_2": "12MM 2400X1200MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 34.66,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 34.65,
    "Billing_Cost": 101,
    "Available_Larvik": 7488.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 75,
    "Antall_I_Bestilling": 2.1,
    "Transitt": 0,
    "Leverandørnr": 100707,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1620,
    "Product_Code": 162001604224001200,
    "NOBB": 50983637,
    "Description": "KONSTR XF FURU SUDPLY TG2",
    "Description_2": "16MM 2400X1200MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 43.45,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 43.45,
    "Billing_Cost": 120,
    "Available_Larvik": 8703.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 37,
    "Antall_I_Bestilling": 720,
    "Transitt": 0,
    "Leverandørnr": 100707,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1620,
    "Product_Code": 162001804224001200,
    "NOBB": 50983622,
    "Description": "KONSTR XF FURU SUDPLY TG2",
    "Description_2": "18MM 2400X1200MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 51.38,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 51.34,
    "Billing_Cost": 148,
    "Available_Larvik": 4911.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 2.5,
    "Transitt": 0,
    "Leverandørnr": 100707,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1630,
    "Product_Code": 163000900023401200,
    "NOBB": 47164285,
    "Description": "KRYSSFINER SOPP/RÅTE BEH TG2",
    "Description_2": "9MM 2340X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 46.5,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 46.5,
    "Billing_Cost": 136,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100445,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1630,
    "Product_Code": 163000900027601200,
    "NOBB": null,
    "Description": "KRYSSFINER SOPP/RÅTE BEH SK",
    "Description_2": "9MM 2760X1200MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 41,
    "Billing_Cost": 0,
    "Available_Larvik": -450.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 500,
    "Antall_I_Bestilling": 1.35,
    "Transitt": 0,
    "Leverandørnr": 101462,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1630,
    "Product_Code": 163000900027601200,
    "NOBB": 47164293,
    "Description": "KRYSSFINER SOPP/RÅTE BEH TG2",
    "Description_2": "9MM 2760X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 51.2,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 51.2,
    "Billing_Cost": 140,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100445,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1630,
    "Product_Code": 163000904424001200,
    "NOBB": 47557932,
    "Description": "KONST XF MOULDGUARD SK",
    "Description_2": "9MM 2400X1200MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 0,
    "Billing_Cost": 117,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100683,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1630,
    "Product_Code": 163001204224001200,
    "NOBB": 47557943,
    "Description": "KONST XF MOULDGUARD TG2",
    "Description_2": "12MM 2400X1207MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 0,
    "Billing_Cost": 148,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100683,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1630,
    "Product_Code": 163001604224001200,
    "NOBB": 47557958,
    "Description": "KONST XF MOULDGUARD TG2",
    "Description_2": "16MM 2400X1207MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 63.34,
    "Billing_Cost": 187,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100683,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1640,
    "Product_Code": 164000000000000000,
    "NOBB": null,
    "Description": "DIVERSE BRANNHEMMENDE X-FINER",
    "Description_2": "",
    "Storageunit": "M2",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 212.77,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 212.77,
    "Billing_Cost": 573,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1640,
    "Product_Code": 164001202024401200,
    "NOBB": 47271401,
    "Description": "KRYSSFINER BRANNX B B/BB",
    "Description_2": "12MM 2440X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 171.71,
    "Billing_Cost_Andalsnes": 170.6,
    "Billing_Cost_Drammen": 170.6,
    "Billing_Cost": 418,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 60,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1640,
    "Product_Code": 164001204324100600,
    "NOBB": 47164796,
    "Description": "KRYSSFINER BRANNX S TG4",
    "Description_2": "12MM 2410X0610MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 112.65,
    "Billing_Cost_Drammen": 112.65,
    "Billing_Cost": 345,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 464,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1640,
    "Product_Code": 164001602424401200,
    "NOBB": 49668477,
    "Description": "KRYSSFINER BRANNX B BB/CP",
    "Description_2": "16MM 2440X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 161.14,
    "Billing_Cost_Drammen": 161.14,
    "Billing_Cost": 807,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 40,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1640,
    "Product_Code": 164001604224001200,
    "NOBB": 47164853,
    "Description": "KRYSSFINER FIRE RESIST TG2(S2)",
    "Description_2": "16MM 2400X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 125,
    "Billing_Cost_Andalsnes": 116.82,
    "Billing_Cost_Drammen": 116.82,
    "Billing_Cost": 377,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 122,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1640,
    "Product_Code": 164001804224001200,
    "NOBB": 47164845,
    "Description": "KRYSSFINER FIRE RESIST TG2(S2)",
    "Description_2": "18MM 2400X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 130.28,
    "Billing_Cost_Drammen": 131.52,
    "Billing_Cost": 453,
    "Available_Larvik": 66.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": 100719,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1640,
    "Product_Code": 164001804324100600,
    "NOBB": 47164800,
    "Description": "KRYSSFINER BRANNX S TG4",
    "Description_2": "18MM 2410X0610MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 162.41,
    "Billing_Cost_Drammen": 162.41,
    "Billing_Cost": 474,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 336,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1640,
    "Product_Code": 164001804524401200,
    "NOBB": null,
    "Description": "KRYSSFINER BRANNX P",
    "Description_2": "18MM 2440X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 188.76,
    "Billing_Cost_Drammen": 184.94,
    "Billing_Cost": 429,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 44,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1640,
    "Product_Code": 164002104324100600,
    "NOBB": 47164816,
    "Description": "KRYSSFINER BRANNX S TG4",
    "Description_2": "21MM 2410X0610MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 187.42,
    "Billing_Cost_Andalsnes": 192.3,
    "Billing_Cost_Drammen": 192.3,
    "Billing_Cost": 571,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": -56,
    "Available_Drammen": 0,
    "Antall_I_ordre": 56,
    "Antall_I_Bestilling": 1.17,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1640,
    "Product_Code": 164002404324100600,
    "NOBB": 47164826,
    "Description": "KRYSSFINER BRANNX S TG4",
    "Description_2": "24MM 2410X0610MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 235.14,
    "Billing_Cost_Andalsnes": 219.76,
    "Billing_Cost_Drammen": 198.36,
    "Billing_Cost": 661,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 112,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 640,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1640,
    "Product_Code": 164002804524401200,
    "NOBB": null,
    "Description": "KRYSSFINER BRANNX P",
    "Description_2": "28MM 2440X1220MM",
    "Storageunit": "PLA",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 0,
    "Billing_Cost_Drammen": 297.28,
    "Billing_Cost": 0,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 35,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  },
  {
    "Product_Category_Code": 16,
    "Product_Group": 1640,
    "Product_Code": 164010000000000000,
    "NOBB": null,
    "Description": "DIVERSE KRYSSFINER BRANNX",
    "Description_2": "",
    "Storageunit": "M2",
    "Billingunit": "M2",
    "Billing_Cost_Larvik": 0,
    "Billing_Cost_Andalsnes": 88.46,
    "Billing_Cost_Drammen": 88.46,
    "Billing_Cost": 573,
    "Available_Larvik": 0.00,
    "Available_Andalsnes": 0,
    "Available_Drammen": 0,
    "Antall_I_ordre": 0,
    "Antall_I_Bestilling": 0,
    "Transitt": 0,
    "Leverandørnr": null,
    "Kolonne1": null,
    "Kolonne2": null,
    "Varesporingskode": null,
    "Product_Category_Name": "Product_Category_Name",
    "Product_Group_Name": "Product_Group_Name"
  }
]*/